"""Embed ../../phone.html into sos_node1/page.h so the ESP32 serves the same SOS page."""
import os, re
here = os.path.dirname(os.path.abspath(__file__))
html = open(os.path.join(here, "..", "phone.html"), encoding="utf-8").read()
html = re.sub(r'<link rel="(stylesheet|icon)"[^>]*>', "", html)   # no fonts / icon files on the node
assert ")rawpage\"" not in html
out = '// generated by build_page.py from phone.html - do not edit\n#pragma once\nconst char PAGE[] PROGMEM = R"rawpage(' + html + ')rawpage";\n'
open(os.path.join(here, "sos_node1", "page.h"), "w", encoding="utf-8").write(out)
print("page.h", len(html.encode()), "bytes")
